version: 0.0
os: linux
files:
  - source: /
    destination: /usr/app/accad-demo-flask
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ec2-user